protocols                = imap lmtp
listen                   = *
haproxy_trusted_networks = 10.0.0.0/8

mail_location     = maildir:/var/spool/mail/vhosts/%d/%n
valid_chroot_dirs = /var/spool/mail
first_valid_uid   = 0
first_valid_gid   = 0
mail_uid          = postmaster
mail_gid          = root

log_path             = /dev/stdout
mail_debug           = yes
lmtp_verbose_replies = yes

auth_mechanisms = plain login

passdb {
  driver         = passwd-file
  args           = /etc/dovecot/passwd
  default_fields = home=/var/spool/mail/vhosts/%d/%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    user  = postfix
    group = root
    mode  = 0660
  }
}

service lmtp {
 unix_listener /var/spool/postfix/private/dovecot-lmtp {
   user  = postfix
   group = root
   mode  = 0660
  }
}

service imap-login {
  inet_listener imap {
    port    = 143
    haproxy = yes
  }
  # inet_listener imaps {
  #   port    = 993
  #   ssl     = yes
  #   haproxy = yes
  # }
}
