Mode               sv

KeyTable           refile:/etc/opendkim/KeyTable
SigningTable       refile:/etc/opendkim/SigningTable
ExternalIgnoreList file:/etc/opendkim/TrustedHosts
InternalHosts      file:/etc/opendkim/TrustedHosts

SignHeaders        MIME-Version,References,In-Reply-To,From,Sender,Date,Message-Id,Subject,To,CC,Reply-To,Content-Type
OversignHeaders    MIME-Version,References,In-Reply-To,From,Sender,Date,Message-Id,Subject,To,CC,Reply-To,Content-Type

AlwaysAddARHeader  Yes

Socket             unix:/var/spool/postfix/private/opendkim
UserID             root:postfix
UMask              0660
RequireSafeKeys    No

Syslog             Yes
SyslogSuccess      Yes
LogWhy             Yes
