Mode               sv

Syslog             Yes
SyslogSuccess      Yes
LogWhy             Yes

KeyTable           refile:/etc/opendkim/KeyTable
SigningTable       refile:/etc/opendkim/SigningTable
ExternalIgnoreList file:/etc/opendkim/TrustedHosts
InternalHosts      file:/etc/opendkim/TrustedHosts

Socket             local:/var/spool/postfix/private/opendkim
UserID             postfix:postfix
