worker "rspamd_proxy" {
    .include "$CONFDIR/worker-proxy.inc"
    .include(try=true; priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/worker-proxy.inc"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-proxy.inc"

    milter  = yes;
    timeout = 120s;

    upstream "local" {
      default   = yes;
      self_scan = yes;
    }

    bind_socket = "localhost:11333";

    milter  = yes;
    timeout = 120s;

    upstream "local" {
      default   = yes;
      self_scan = yes;
    }

    count                = 1;
    max_retries          = 5;
    discard_on_reject    = false;
    quarantine_on_reject = false;
    spam_header          = "X-Spam";
    reject_message       = "Spam message rejected";
}
